"use client";

import { BuilderButton } from "@/components/resume-builder/FormFields";
import { useResumeBuilder } from "@/context/ResumeBuilderContext";

export default function SuggestionPanel() {
  const { state, dispatch } = useResumeBuilder();
  const pending = state.pendingSuggestion;

  if (!pending) return null;

  return (
    <div
      className="builder-suggestion"
      role="dialog"
      aria-labelledby="suggestion-title"
    >
      <h3 id="suggestion-title" className="builder-section-title text-base mb-2">
        Review generated content
      </h3>
      <p className="text-sm text-[var(--color-grey)] mb-4">
        This content was generated by AI. Review it carefully before accepting.
        Nothing is applied until you accept.
      </p>
      {pending.originalText ? (
        <div className="mb-4">
          <p className="label-caps text-xs text-[var(--color-grey)] mb-1">Original</p>
          <p className="text-sm whitespace-pre-wrap">{pending.originalText}</p>
        </div>
      ) : null}
      <div className="mb-4">
        <p className="label-caps text-xs text-[var(--color-grey)] mb-1">Suggested</p>
        <p className="text-sm whitespace-pre-wrap">{pending.content}</p>
      </div>
      <div className="flex flex-wrap gap-2">
        <BuilderButton
          variant="primary"
          onClick={() => dispatch({ type: "ACCEPT_PENDING_SUGGESTION" })}
        >
          Accept
        </BuilderButton>
        <BuilderButton
          variant="secondary"
          onClick={() => dispatch({ type: "SET_PENDING_SUGGESTION", pending: null })}
        >
          Cancel
        </BuilderButton>
      </div>
    </div>
  );
}
